# Generated by Django 6.0 on 2025-12-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
